package myhibernate;
// Generated Mar 29, 2017 7:27:25 PM by Hibernate Tools 4.3.1



/**
 * Admintable generated by hbm2java
 */
public class Admintable  implements java.io.Serializable {


     private String username;
     private String password;

    public Admintable() {
    }

    public Admintable(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


