package myhibernate;
// Generated Mar 29, 2017 7:27:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categorytable generated by hbm2java
 */
public class Categorytable  implements java.io.Serializable {


     private Integer catid;
     private String catname;
     private String image;
     private Set subcategories = new HashSet(0);
     private Set producttables = new HashSet(0);

    public Categorytable() {
    }

	
    public Categorytable(String catname, String image) {
        this.catname = catname;
        this.image = image;
    }
    public Categorytable(String catname, String image, Set subcategories, Set producttables) {
       this.catname = catname;
       this.image = image;
       this.subcategories = subcategories;
       this.producttables = producttables;
    }
   
    public Integer getCatid() {
        return this.catid;
    }
    
    public void setCatid(Integer catid) {
        this.catid = catid;
    }
    public String getCatname() {
        return this.catname;
    }
    
    public void setCatname(String catname) {
        this.catname = catname;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Set getSubcategories() {
        return this.subcategories;
    }
    
    public void setSubcategories(Set subcategories) {
        this.subcategories = subcategories;
    }
    public Set getProducttables() {
        return this.producttables;
    }
    
    public void setProducttables(Set producttables) {
        this.producttables = producttables;
    }




}


