package myhibernate;
// Generated Mar 29, 2017 7:27:25 PM by Hibernate Tools 4.3.1



/**
 * Contactus generated by hbm2java
 */
public class Contactus  implements java.io.Serializable {


     private Integer srno;
     private String name;
     private String emailid;
     private String phone;
     private String message;

    public Contactus() {
    }

    public Contactus(String name, String emailid, String phone, String message) {
       this.name = name;
       this.emailid = emailid;
       this.phone = phone;
       this.message = message;
    }
   
    public Integer getSrno() {
        return this.srno;
    }
    
    public void setSrno(Integer srno) {
        this.srno = srno;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmailid() {
        return this.emailid;
    }
    
    public void setEmailid(String emailid) {
        this.emailid = emailid;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }




}


