package myhibernate;
// Generated Mar 29, 2017 7:27:25 PM by Hibernate Tools 4.3.1



/**
 * Producttable generated by hbm2java
 */
public class Producttable  implements java.io.Serializable {


     private Integer productid;
     private Categorytable categorytable;
     private Subcategory subcategory;
     private String name;
     private int price;
     private String features;
     private String image;
     private int qty;

    public Producttable() {
    }

    public Producttable(Categorytable categorytable, Subcategory subcategory, String name, int price, String features, String image, int qty) {
       this.categorytable = categorytable;
       this.subcategory = subcategory;
       this.name = name;
       this.price = price;
       this.features = features;
       this.image = image;
       this.qty = qty;
    }
   
    public Integer getProductid() {
        return this.productid;
    }
    
    public void setProductid(Integer productid) {
        this.productid = productid;
    }
    public Categorytable getCategorytable() {
        return this.categorytable;
    }
    
    public void setCategorytable(Categorytable categorytable) {
        this.categorytable = categorytable;
    }
    public Subcategory getSubcategory() {
        return this.subcategory;
    }
    
    public void setSubcategory(Subcategory subcategory) {
        this.subcategory = subcategory;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public String getFeatures() {
        return this.features;
    }
    
    public void setFeatures(String features) {
        this.features = features;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }




}


