package myhibernate;
// Generated Mar 29, 2017 7:27:25 PM by Hibernate Tools 4.3.1



/**
 * Usertable generated by hbm2java
 */
public class Usertable  implements java.io.Serializable {


     private String username;
     private String password;
     private String name;
     private String address;
     private String phone;
     private String emailid;
     private String gender;
     private String country;

    public Usertable() {
    }

    public Usertable(String username, String password, String name, String address, String phone, String emailid, String gender, String country) {
       this.username = username;
       this.password = password;
       this.name = name;
       this.address = address;
       this.phone = phone;
       this.emailid = emailid;
       this.gender = gender;
       this.country = country;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmailid() {
        return this.emailid;
    }
    
    public void setEmailid(String emailid) {
        this.emailid = emailid;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }




}


